我们这一讲的话呢，我们继续研究HystrixInvocationHandler里面的东西

 

接口：Interface

服务接口：接口，Interface里面的一个方法 => 一个服务的一个接口

 

看了一下请求处理的入口，HystrixInvocationHandler.invoke()跟进去，看了一个setterMethodMap，ServiceAClient里面的每个接口方法都有一个hystirx的Setter，包含了groupKey（服务名称，ServiceA），commandKey（接口名称，ServiceAClient#sayHello(Long,String,Integer)）

 

基于这个被调用的方法的Setter，构造了一个HystrixCommand

 

我们来研究一下HystrixCommand的组成结构

 

   @Override

   protected Object run() throws Exception {

​    try {

​     return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);

​    } catch (Exception e) {

​     throw e;

​    } catch (Throwable t) {

​     throw (Error) t;

​    }

   }

 

   @Override

   protected Object getFallback() {

​    if (fallbackFactory == null) {

​     return super.getFallback();

​    }

​    try {

​     Object fallback = fallbackFactory.create(getExecutionException());

​     Object result = fallbackMethodMap.get(method).invoke(fallback, args);

​     if (isReturnsHystrixCommand(method)) {

​      return ((HystrixCommand) result).execute();

​     } else if (isReturnsObservable(method)) {

​      // Create a cold Observable

​      return ((Observable) result).toBlocking().first();

​     } else if (isReturnsSingle(method)) {

​      // Create a cold Observable as a Single

​      return ((Single) result).toObservable().toBlocking().first();

​     } else if (isReturnsCompletable(method)) {

​      ((Completable) result).await();

​      return null;

​     } else {

​      return result;

​     }

​    } catch (IllegalAccessException e) {

​     // shouldn't happen as method is public due to being an interface

​     throw new AssertionError(e);

​    } catch (InvocationTargetException e) {

​     // Exceptions on fallback are tossed by Hystrix

​     throw new AssertionError(e.getCause());

​    }

   }

 

上面的那坨代码，要仔细研究，他就是HystrixCommand的组成结构

 

   @Override

   protected Object run() throws Exception {

​    try {

​     return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);

​    } catch (Exception e) {

​     throw e;

​    } catch (Throwable t) {

​     throw (Error) t;

​    }

   }

 

run()方法，HystrixCommand的run方法里面是什么东东？command实际执行的时候，他的业务逻辑就封装在了这个里面

 

对于我们来说，每个command的执行业务逻辑，就是根据ribbon进行负载均衡，选择一个server，生成针对那个server的http请求，发起一个http请求

 

command核心的执行逻辑，就是下面那行代码

 

return HystrixInvocationHandler.this.dispatch.get(method).invoke(args);

 

dispatch：map数据结构，接口里每个方法Method -> SynchronousMethodHandler

 

SynchronousMethodHandler.invoke()，传入执行这个方法的实际的参数，args

 

这个里面的执行逻辑，就跟我们之前讲解的feign的原生的请求执行逻辑是一样的了

 

   @Override

   protected Object getFallback() {

​    if (fallbackFactory == null) {

​     return super.getFallback();

​    }

​    try {

​     Object fallback = fallbackFactory.create(getExecutionException());

​     Object result = fallbackMethodMap.get(method).invoke(fallback, args);

​     if (isReturnsHystrixCommand(method)) {

​      return ((HystrixCommand) result).execute();

​     } else if (isReturnsObservable(method)) {

​      // Create a cold Observable

​      return ((Observable) result).toBlocking().first();

​     } else if (isReturnsSingle(method)) {

​      // Create a cold Observable as a Single

​      return ((Single) result).toObservable().toBlocking().first();

​     } else if (isReturnsCompletable(method)) {

​      ((Completable) result).await();

​      return null;

​     } else {

​      return result;

​     }

​    } catch (IllegalAccessException e) {

​     // shouldn't happen as method is public due to being an interface

​     throw new AssertionError(e);

​    } catch (InvocationTargetException e) {

​     // Exceptions on fallback are tossed by Hystrix

​     throw new AssertionError(e.getCause());

​    }

   }

 

你觉得这里的getFallback()方法被调用，应该是什么时候？

 

我告诉大家，就是在你的hystrix command执行发生问题的时候，会调用这个command的fallback逻辑，降级机制：熔断（断路器打开了，直接就会fallback）、拒绝（线程池满了，信号量满了）、超时（核心逻辑执行超时）、异常（如果核心逻辑执行报错，比如说远程接口报错，往外面抛异常）

 

上述的情况下，会直接执行getFallback()方法，去获取一个Fallback object，降级对象，然后会调用这个fallback对象中的降级方法，来实现降级逻辑

 

netflix hystrix的github上拉取源码，1.5.12

 

如果fallbackFactory是null的话，直接会报错，就说你没有fallback降级逻辑，结果你的command还执行失败了，此时就会直接给你报错

 

Object fallback = fallbackFactory.create(getExecutionException());

 

fallbackFactory去创建一个fallback对象出来，getExecutionException是什么东西？获取command执行的异常，熔断、拒绝、超时、报错，都会给你，你自己来决定，根据各种不同的异常，如何实现降级

 

Object fallback：我们自己定义的实现ServiceAClient接口的匿名类的对象，里面包含了降级的逻辑

 

Object result = fallbackMethodMap.get(method).invoke(fallback, args);

 

fallbackMethodMap一看就是包含了接口的各种方法，根据你要调用的这个方法，获取一个方法对应的Method对象，然后对fallback object调用那个Method方法，传入args参数

 

这一讲，咱们就剖析清楚了，在这里创建的这个HystrixCommand的结构

 

run()，getFallback()

 

run()：就是使用SynchronousMethodHandler来处理请求，逻辑跟之前是一模一样了

 

getFallback()：就是如果command执行有任何的问题的话，就会直接获取一个fallback object，然后执行fallback object的降级逻辑

 

 